###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_DATABASE=blog-php
            - MYSQL_USER=dbadmin
            - MYSQL_PASSWORD=123456
        ports:
            - '64002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '64000:80'
        links:
            - php-fpm
    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        links:
            - mysql
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
